######################################################################
# Automatically generated by qmake (2.01a) Di 12. Jan 20:17:54 2010
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../test.h \
           ../../testtypes.h \
           ../../googletest.h \
           ../../qtestlibtest.h
SOURCES += TestTheTests.cpp \
           ../../test.cpp \
           ../../googletest.cpp \
           ../../qtestlibtest.cpp
